stages:
  - build
  - deploy

variables:
  IMAGE_TAG: latest

before_script:
  - apk add --no-cache python3 py3-pip
  - pip3 install --upgrade pip
  - pip3 install awscli
  - $(aws ecr get-login --no-include-email --region $AWS_DEFAULT_REGION)

build:
  stage: build
  script:
    - docker build -t raygun3491/s3upload:$IMAGE_TAG .
    - docker push raygun3491/s3upload:$IMAGE_TAG
  only:
    - main

deploy:
  stage: deploy
  script:
    - aws ecs update-service --cluster $CI_AWS_ECS_CLUSTER --service $CI_AWS_ECS_SERVICE --force-new-deployment
  only:
    - main
