stages:
  - build
  - deploy

variables:
  IMAGE_TAG: latest

before_script:
  - apk add --no-cache python3 py3-pip
  - pip3 install --upgrade pip
  - pip3 install awscli

build:
  stage: build
  image: docker:20.10.17
  services:
    - docker:20.10.17-dind
  script:
    - python3 -m venv venv
    - source venv/bin/activate
    - aws ecr get-login-password --region $AWS_DEFAULT_REGION
    - echo "$DOCKERHUB_PASSWORD" | docker login -u "$DOCKERHUB_USERNAME" --password-stdin
    - docker build -t raygun3491/s3upload:$IMAGE_TAG .
    - docker push raygun3491/s3upload:$IMAGE_TAG
  only:
    - main

deploy:
  stage: deploy
  image: python:3.8-alpine
  script:
    - pip install --upgrade awscli
    - aws ecs update-service --cluster $CI_AWS_ECS_CLUSTER --service $CI_AWS_ECS_SERVICE --force-new-deployment
  only:
    - main
